spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data: # spring data rest - 관련 설정
    rest:
      base-path: /api  #endpoint start path
      detection-strategy: annotated
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key: adsadsadasdasdasdasdasdasd123213123123123123####
  access-token-expiration-minutes: 10
  refresh-token-expiration-minutes: 420